#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v20
# autospec commit: a19cdc79b421
#
Name     : coinmp
Version  : 1.8.4+dfsg
Release  : 8
URL      : https://mirrors.kernel.org/debian/pool/main/c/coinmp/coinmp_1.8.4+dfsg.orig.tar.xz
Source0  : https://mirrors.kernel.org/debian/pool/main/c/coinmp/coinmp_1.8.4+dfsg.orig.tar.xz
Summary  : Simple C API for COIN-OR Solvers Clp and Cbc
Group    : Development/Tools
License  : CPL-1.0
Requires: coinmp-data = %{version}-%{release}
Requires: coinmp-lib = %{version}-%{release}
Requires: coinmp-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : bzip2-dev
BuildRequires : gfortran
BuildRequires : pkgconfig(cbc)
BuildRequires : pkgconfig(clp)
BuildRequires : pkgconfig(osi-clp)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=============

Bjarni Kristjansson

%package data
Summary: data components for the coinmp package.
Group: Data

%description data
data components for the coinmp package.


%package dev
Summary: dev components for the coinmp package.
Group: Development
Requires: coinmp-lib = %{version}-%{release}
Requires: coinmp-data = %{version}-%{release}
Provides: coinmp-devel = %{version}-%{release}
Requires: coinmp = %{version}-%{release}

%description dev
dev components for the coinmp package.


%package lib
Summary: lib components for the coinmp package.
Group: Libraries
Requires: coinmp-data = %{version}-%{release}
Requires: coinmp-license = %{version}-%{release}

%description lib
lib components for the coinmp package.


%package license
Summary: license components for the coinmp package.
Group: Default

%description license
license components for the coinmp package.


%prep
%setup -q -n CoinMP
cd %{_builddir}/CoinMP

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1727384264
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1727384264
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/coinmp
cp %{_builddir}/CoinMP/CoinMP/LICENSE %{buildroot}/usr/share/package-licenses/coinmp/36830cfb4da96520f326b26f69a9f2dc5f81f971 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## install_append content
rm -rf %{buildroot}/builddir
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/coin/Data/Sample/afiro.mps
/usr/share/coin/Data/Sample/app0110.cor
/usr/share/coin/Data/Sample/app0110.stoch
/usr/share/coin/Data/Sample/app0110.time
/usr/share/coin/Data/Sample/app0110R.cor
/usr/share/coin/Data/Sample/app0110R.stoch
/usr/share/coin/Data/Sample/app0110R.time
/usr/share/coin/Data/Sample/atm_5_10_1.block
/usr/share/coin/Data/Sample/atm_5_10_1.mps
/usr/share/coin/Data/Sample/block_milp.dec
/usr/share/coin/Data/Sample/block_milp.lp
/usr/share/coin/Data/Sample/brandy.mps
/usr/share/coin/Data/Sample/bug.cor
/usr/share/coin/Data/Sample/bug.stoch
/usr/share/coin/Data/Sample/bug.time
/usr/share/coin/Data/Sample/conic.mps
/usr/share/coin/Data/Sample/e226.mps
/usr/share/coin/Data/Sample/exmip1.5.mps
/usr/share/coin/Data/Sample/exmip1.lp
/usr/share/coin/Data/Sample/exmip1.mps
/usr/share/coin/Data/Sample/finnis.mps
/usr/share/coin/Data/Sample/galenet.mps
/usr/share/coin/Data/Sample/galenetbnds.mps
/usr/share/coin/Data/Sample/hello.mps
/usr/share/coin/Data/Sample/input.130
/usr/share/coin/Data/Sample/lseu.mps
/usr/share/coin/Data/Sample/nw460.mps
/usr/share/coin/Data/Sample/p0033.mps
/usr/share/coin/Data/Sample/p0201.mps
/usr/share/coin/Data/Sample/p0548.mps
/usr/share/coin/Data/Sample/pack1.mps
/usr/share/coin/Data/Sample/retail3.block
/usr/share/coin/Data/Sample/retail3.mps
/usr/share/coin/Data/Sample/scOneInt.mps
/usr/share/coin/Data/Sample/share2qp.mps
/usr/share/coin/Data/Sample/spec_sections.mps
/usr/share/coin/Data/Sample/tp3.mps
/usr/share/coin/Data/Sample/tp4.mps
/usr/share/coin/Data/Sample/tp5.mps
/usr/share/coin/Data/Sample/wedding_16.block
/usr/share/coin/Data/Sample/wedding_16.mps
/usr/share/coin/doc/CoinMP/AUTHORS
/usr/share/coin/doc/CoinMP/LICENSE
/usr/share/coin/doc/CoinMP/README
/usr/share/coin/doc/CoinMP/coinmp_addlibs.txt

%files dev
%defattr(-,root,root,-)
/usr/include/coin/CoinMP.h
/usr/include/coin/CoinMPConfig.h
/usr/lib64/libCoinMP.so
/usr/lib64/pkgconfig/coindatasample.pc
/usr/lib64/pkgconfig/coinmp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libCoinMP.so.0
/usr/lib64/libCoinMP.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/coinmp/36830cfb4da96520f326b26f69a9f2dc5f81f971
